### PR TITLE
Fix for regex module compatibility

### PR DESCRIPTION
**Pull request by mizumm**
Without this patch, error occurs on tests/testasciidoc3.py.

$ python3 tests/testasciidoc3.py run 1
1: Test cases
SOURCE: asciidoc3: tests/data/testcases.txt
Traceback (most recent call last):
  File "/home/FOO/Downloads/asciidoc3/asciidoc3.py", line 6042, in asciidoc3
    if not config.load_from_dirs('asciidoc3.conf', include=['attributes']):
...
  File "/home/FOO/Downloads/asciidoc3/asciidoc3.py", line 4271, in match
    if re.match(name, mo.group('name')):
  File "/usr/lib/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.6/sre_parse.py", line 502, in _parse
    code = _escape(source, this, state)
  File "/usr/lib/python3.6/sre_parse.py", line 401, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
sre_constants.error: bad escape \i at position 28

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/FOO/Downloads/asciidoc3/tests/asciidoc3api.py", line 224, in execute
    self.asciidoc3.execute(self.cmd, opts.values, args)
  File "/home/FOO/Downloads/asciidoc3/asciidoc3.py", line 6316, in execute
    asciidoc3(backend, doctype, confiles, infile, outfile, options)
  File "/home/FOO/Downloads/asciidoc3/asciidoc3.py", line 6175, in asciidoc3
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/testasciidoc3.py", line 429, in <module>
    tests.run(number, backend)
  File "tests/testasciidoc3.py", line 327, in run
    test.run(backend)
  File "tests/testasciidoc3.py", line 245, in run
    got = self.generate_expected(backend)
  File "tests/testasciidoc3.py", line 196, in generate_expected
    asciidoc3.execute(infile, outfile, backend)
  File "/home/FOO/Downloads/asciidoc3/tests/asciidoc3api.py", line 229, in execute
    raise AsciiDoc3Error(self.messages[-1])
asciidoc3api.AsciiDoc3Error: FAILED: unexpected error: bad escape \i at position 28

### CODE REVIEW

**Comment by MasterOdin** [comment]
It should also be added somewhere that this relies on the [regex module from pypi](https://pypi.org/project/regex/).

**Comment by asciidoc3** [comment]
@MasterOdin @mizumm,
I can reproduce this, more or less: but interestingly different tracebacks pop up depending on the Python version (3.5 vs 3.6) and/or the os (Ubuntu vs Debian vs BSD). 
And a second notice: some tracebacks regarding ‚module asciidoc3 not found‘ in asciidoc3api.py, others ‚file not found‘ in asciidoc3.py – I don‘t see any regex errors here.
BTW @MasterOdin, you use ‚/srv/asciidoc‘ - only curious, that should not be of any relevance – are asciidoc.py or other files of the Python2 distribution living in this directory, too?
I think it‘s desirable (very important), not to rely on pypi-modules, AsciiDoc3 should run with built-ins only.
Think, I need some more testing here ...

**Comment by MasterOdin** [comment]
It's the mount point I used in a Dockerfile I created (https://github.com/asciidoc/asciidoc-py3/blob/master/Dockerfile) to make it easier to test asciidoc3 as I had issues setting up lilypond on my Mac via homebrew. I mounted the directory that housed this repo into the Dockerfile at `/srv/asciidoc`.

**Comment by mizumm** [comment]
@asciidoc3 I have updated the pull request to fix the other regex module compatibility.

**Comment by mizumm** [comment]
@asciidoc3 And, I have fixed 2 bugs. There may be the bug you hit... I would appreciate it if you could check my devel branch.

**Comment by asciidoc3** [comment]
See asciidoc3/asciidoc3

**Pull request closed without merging**
